# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import world_pb2 as world__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in world_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorldServiceStub(object):
    """interact with the world model
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEntities = channel.unary_unary(
                '/world.WorldService/ListEntities',
                request_serializer=world__pb2.ListEntitiesRequest.SerializeToString,
                response_deserializer=world__pb2.ListEntitiesResponse.FromString,
                _registered_method=True)
        self.GetEntity = channel.unary_unary(
                '/world.WorldService/GetEntity',
                request_serializer=world__pb2.GetEntityRequest.SerializeToString,
                response_deserializer=world__pb2.GetEntityResponse.FromString,
                _registered_method=True)
        self.WatchEntities = channel.unary_stream(
                '/world.WorldService/WatchEntities',
                request_serializer=world__pb2.ListEntitiesRequest.SerializeToString,
                response_deserializer=world__pb2.EntityChangeEvent.FromString,
                _registered_method=True)
        self.Push = channel.unary_unary(
                '/world.WorldService/Push',
                request_serializer=world__pb2.EntityChangeRequest.SerializeToString,
                response_deserializer=world__pb2.EntityChangeResponse.FromString,
                _registered_method=True)
        self.ExpireEntity = channel.unary_unary(
                '/world.WorldService/ExpireEntity',
                request_serializer=world__pb2.ExpireEntityRequest.SerializeToString,
                response_deserializer=world__pb2.ExpireEntityResponse.FromString,
                _registered_method=True)
        self.GetLocalNode = channel.unary_unary(
                '/world.WorldService/GetLocalNode',
                request_serializer=world__pb2.GetLocalNodeRequest.SerializeToString,
                response_deserializer=world__pb2.GetLocalNodeResponse.FromString,
                _registered_method=True)
        self.RunTask = channel.unary_unary(
                '/world.WorldService/RunTask',
                request_serializer=world__pb2.RunTaskRequest.SerializeToString,
                response_deserializer=world__pb2.RunTaskResponse.FromString,
                _registered_method=True)


class WorldServiceServicer(object):
    """interact with the world model
    """

    def ListEntities(self, request, context):
        """list entities present in the world once
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """request every detail about one entity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEntities(self, request, context):
        """continously monitor entities present in the world. this is used by downstream C2.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request, context):
        """Create or update an entity. Used by capabilities.

        Push uses merge semantics: only components present (set) in the pushed entity
        are updated. Components not included in the message are left unchanged.
        Components cannot be removed once set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpireEntity(self, request, context):
        """expire an entity, setting its lifetime.until to now
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalNode(self, request, context):
        """get information about the local node the client is connected to
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTask(self, request, context):
        """create an instance of a specific task entity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorldServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntities,
                    request_deserializer=world__pb2.ListEntitiesRequest.FromString,
                    response_serializer=world__pb2.ListEntitiesResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=world__pb2.GetEntityRequest.FromString,
                    response_serializer=world__pb2.GetEntityResponse.SerializeToString,
            ),
            'WatchEntities': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEntities,
                    request_deserializer=world__pb2.ListEntitiesRequest.FromString,
                    response_serializer=world__pb2.EntityChangeEvent.SerializeToString,
            ),
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=world__pb2.EntityChangeRequest.FromString,
                    response_serializer=world__pb2.EntityChangeResponse.SerializeToString,
            ),
            'ExpireEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpireEntity,
                    request_deserializer=world__pb2.ExpireEntityRequest.FromString,
                    response_serializer=world__pb2.ExpireEntityResponse.SerializeToString,
            ),
            'GetLocalNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalNode,
                    request_deserializer=world__pb2.GetLocalNodeRequest.FromString,
                    response_serializer=world__pb2.GetLocalNodeResponse.SerializeToString,
            ),
            'RunTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTask,
                    request_deserializer=world__pb2.RunTaskRequest.FromString,
                    response_serializer=world__pb2.RunTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.WorldService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.WorldService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorldService(object):
    """interact with the world model
    """

    @staticmethod
    def ListEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.WorldService/ListEntities',
            world__pb2.ListEntitiesRequest.SerializeToString,
            world__pb2.ListEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.WorldService/GetEntity',
            world__pb2.GetEntityRequest.SerializeToString,
            world__pb2.GetEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.WorldService/WatchEntities',
            world__pb2.ListEntitiesRequest.SerializeToString,
            world__pb2.EntityChangeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.WorldService/Push',
            world__pb2.EntityChangeRequest.SerializeToString,
            world__pb2.EntityChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpireEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.WorldService/ExpireEntity',
            world__pb2.ExpireEntityRequest.SerializeToString,
            world__pb2.ExpireEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocalNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.WorldService/GetLocalNode',
            world__pb2.GetLocalNodeRequest.SerializeToString,
            world__pb2.GetLocalNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.WorldService/RunTask',
            world__pb2.RunTaskRequest.SerializeToString,
            world__pb2.RunTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
